openapi: 3.0.0
info:
  version: v0.0.1
  title: Cesar Australia Web API
  description: Welcome to Cesar Australia Web API. This is an API to query the Cesar database hosted on AWS server.
  contact:
    name: API developer
    email: "rvalavi@cesaraustralia.com"
    url: https://github.com/rvalavi
externalDocs:
  description: Visit Cesar Australia website
  url: https://cesaraustralia.com/

paths:
  /api/chems/all:
    description: Get all chems by this
    get:
      tags:
        - Chemicals
      description: Returns all chems
      # parameters:
      #   - in: query
      #     name: all
      #     required: true
      #     description: get all the chems
      #     schema:
      #       type: string
      #       example: 

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chem'
        '404':
          description: Method Not Found. (Typically means we couldn't find the Id).
          
  /api/chems/id={chemID}:
    description: get chems by id
    get:
      tags:
        - Chemicals
      description: Returns chems by id
      parameters:
        - in: path
          name: chemID
          required: true
          description: get a chemical information by id
          schema:
            type: integer
            example: 5

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chem'
        '404':
          description: Method Not Found. (Typically means we couldn't find the Id).
          
  /api/chems/active={search}:
    description: get chems by searching chem_active
    get:
      tags:
        - Chemicals
      description: Returns chems by search chem_active
      parameters:
        - in: path
          name: search
          required: true
          description: get a chemical information by searching chem_active
          schema:
            type: string
            example: Ace

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/chem'
        '404':
          description: Method Not Found. (Typically means we couldn't find the Id).
          
          
  /api/species/all:
    description: Get all species by this
    get:
      tags:
        - Species
      description: Returns all species
      # parameters:
      #   - in: query
      #     name: all
      #     required: true
      #     description: get all the species
      #     schema:
      #       type: string
      #       example: /api/species

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/species'
        '404':
          description: Method Not Found. (Typically means we couldn't find the Id).
          
  /api/species/name={search}:
    description: get species by searching names
    get:
      tags:
        - Species
      description: Returns species by search names
      parameters:
        - in: path
          name: search
          required: true
          description: get a species information by searching names
          schema:
            type: string
            example: Br

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/species'
        '404':
          description: Method Not Found. The species name not found!
        
        
  # /api/resistance/all:
  #   description: Get all resistance cases by this
  #   get:
  #     tags:
  #       - Resistance
  #     description: Returns all resistance case
  #     # parameters:
  #     #   - in: query
  #     #     name: all
  #     #     required: true
  #     #     description: get all the resistance cases
  #     #     schema:
  #     #       type: string
  #     #       example: /api/resistance/all

  #     responses:
  #       '200':
  #         description: Successful operation
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/resistance'
  #       '404':
  #         description: Method Not Found. (Typically means we couldn't find the Id).

  /api/resistance/id={resistID}:
    description: get resistance by id
    get:
      tags:
        - Resistance
      description: Returns resistance by id
      parameters:
        - in: path
          name: resistID
          required: true
          description: get a resistance case by id
          schema:
            type: integer
            example: 5

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resistance'
        '404':
          description: Method Not Found. (Typically means we couldn't find the Id).

  /api/resistance/locality={search}:
    description: get resistance by searching locality
    get:
      tags:
        - Resistance
      description: Returns resistance by search locality
      parameters:
        - in: path
          name: search
          required: true
          description: get a resistance case by searching locality
          schema:
            type: string
            example: Bell

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resistance'
        '404':
          description: Method Not Found. The species name not found!


components:
  schemas:
    chem:
      type: object
      properties:
        chem_active:
          type: string
          description: The active ingridients
        chem_group:
          type: string
          description: The chemical group
        chem_irac:
          type: string
          description: The chemical IRAC
    species:
      type: object
      properties:
        name:
          type: string
          description: The species scientific name
    resistance:
      type: object
      properties:
        absent_present_aprd:
          type: integer
          description: No description is provided!
        active:
          type: string
          description: The active ingridients
        lat:
          type: number
          description: Latitude of the observation
        long:
          type: number
          description: Longitude of the observation
        locality:
          type: string
          description: Location
        resistance:
          type: integer
          description: Chemical resistance - binary
        severity:
          type: string
          description: The severity of chemical resistance
        species:
          type: string
          description: Name of the species
        storedgrains:
          type: boolean
          description: No description is provided!
        title:
          type: string
          description: The title of the publication reported the resistance case
